export const data =[
    {
        question:"What is the capital city of Japan?",
        option1:" Beijing",
        option2:"tokyo",
        option3:"seoul",
        option4:"Bangkok",
        ans:2,
    },
    {
        question:" What is the chemical symbol for gold?",
        option1:"Au",
        option2:"Ag",
        option3:"Pb",
        option4:"Fe",
        ans:1,
    },
    {
        question:"What is the value of Pi to two decimal places",
        option1:" 3.19",
        option2:" 3.21",
        option3:"3.17",
        option4:"3.14",
        ans:4,
    },
    {
        question:" Which river is the longest in the world?",
        option1:"nile",
        option2:"amazon",
        option3:" Mississippi",
        option4:"none",
        ans:1,
    },
    {
        question:" In which sport is the term birdie used?",
        option1:"Basketball",
        option2:"Tennisr",
        option3:"Golf",
        option4:"Badminton",
        ans:3,
    },
    {
        question:"Which ancient civilization built the pyramids?",
        option1:"Greeks",
        option2:"Egyptians",
        option3:"Aztecs",
        option4:"Romans",
        ans:2,
    },
    {
        question:"What is the powerhouse of the cell? ",
        option1:"Mitochondria",
        option2:"Nucleus",
        option3:" Ribosome",
        option4:"Golgi apparatus",
        ans:1,
    },
    {
        question:" What currency is used in Japan?",
        option1:"Peso",
        option2:"Yaun",
        option3:" Won",
        option4:"Yen",
        ans:4,
    },
    {
        question:"Which continent is the Sahara Desert located on?",
        option1:"Australia",
        option2:"Asia",
        option3:"Africa",
        option4:"South America",
        ans:3,
    },
    {
        question:"What is the closest planet to the Sun?",
        option1:"Mercury",
        option2:"Venus",
        option3:"Mars",
        option4:"Jupiter",
        ans:1,
    },
]